#!/bin/bash
echo ""
echo "Formatting top level c files"
uncrustify -c kr-indent.cfg *.c
rm -f *.c
find -type f -name '*.uncrustify' -print0 | while read -d $'\0' f; do mv "$f" "${f%.uncrustify}"; done

echo "Formatting libsr c files"
cd libsrc
uncrustify -c ../kr-indent.cfg *.c
rm -f *.c
find -type f -name '*.uncrustify' -print0 | while read -d $'\0' f; do mv "$f" "${f%.uncrustify}"; done

cd ..

export LD_LIBRARY_PATH=:.:lib
make

if (($# > 0))
then
valgrind --leak-check=yes --suppressions=valgrind.supp ./mydash
fi
