#!/bin/sh

case $# in
0) echo "Usage " `basename $0` " <program> [<verbose=true|false>]"; exit 1;;
esac

program=$1
debug=true
if test "$2" != ""
then
	debug=$2
fi


for t in $PWD/test-* ; do
$program < $t/input.txt > $t/output.txt

if test "$debug" = "true"
then
	diff  $t/output.txt $t/correct.txt
else
	diff  $t/output.txt $t/correct.txt >& /dev/null
fi

if test "$?" = "0"
then
	echo ${t##*/} "PASSED!"
else
	echo ${t##*/} "FAILED!"
fi
done


